export {default as categoryReducer} from './category.reducer'
export {default as productReducer} from './product.reducer'
export {default as orderReducer} from './order.reducer'
export {default as cartReducer} from './cart.reducer'
export {default as profileReducer} from './profile.reducer'
export {default as authReducer} from './auth.reducer'